log:
  stdout: true
  level: "${LOG_LEVEL}"

cassandra:
  hosts: "${CASSANDRA_SEEDS}"
  keyspace: "${KEYSPACE}"
  visibilityKeyspace: "${VISIBILITY_KEYSPACE}"
  consistency: "${CASSANDRA_CONSISTENCY}"
  numHistoryShards: ${NUM_HISTORY_SHARDS}
